/**
 * Copyright (C) 2009 - 2009 by OpenGamma Inc.
 *
 * Please see distribution for license.
 */
package com.opengamma.fudge;

/**
 * A Fudge-specific subclass of {@link RuntimeException} for all non-checked-exceptions
 * generated by Fudge. 
 *
 * @author kirk
 */
public class FudgeRuntimeException extends RuntimeException {
  public FudgeRuntimeException(String message) {
    super(message);
  }
  
  public FudgeRuntimeException(String message, Throwable cause) {
    super(message, cause);
  }

}
